---
- hosts: ct
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install a list
      yum:
       name:
        - yum-utils
        - gcc
        - make
        - openssl-devel
        - bzip2-devel
        - libffi-devel
        - xz-devel
        - python3-pip
        - docker-python
        - docker-py
       state: present

    - name: Add Docker Repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: download and install Docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: Create symbolic link
      file:
        src:  "/usr/local/bin/docker-compose"
        dest: "/usr/bin/docker-compose"
        state: link

    - name: Update and install docker-ce
      yum:
       name: docker-ce
       update_cache: yes
       state: latest
      notify:
        - restart docker service

#    - name: Pull centos Docker image
#      docker_image:
#       name: centos
#       pull: yes

    - name: Pull default Docker image
      docker_image:
       name: "{{ default_container_image }}"
       source: pull

    - name: Create default containers
      docker_container:
       name: "{{ default_container_name }}{{ item }}"
       image: "{{ default_container_image }}"
       command: "{{ default_container_command }}"
       state: present
      with_sequence: count={{ create_containers }}
